import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';

const mockExecute = vi.fn();
const mockSelect = vi.fn();

vi.mock('@tauri-apps/plugin-sql', () => ({
  default: {
    load: vi.fn(() =>
      Promise.resolve({
        execute: mockExecute,
        select: mockSelect,
      }),
    ),
  },
}));

vi.mock('../../util', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../../util')>();
  return {
    ...actual,
    generateId: vi.fn(() => 'test-generated-id'),
  };
});

import { create } from '../create';

describe('create', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockExecute.mockResolvedValue({ lastInsertId: 0 });
    mockSelect.mockResolvedValue([]);
  });

  afterEach(() => {
    vi.resetModules();
  });

  it('should insert adventure and return generated ID', async () => {
    mockExecute.mockResolvedValue({});

    const adventureId = await create();

    expect(mockExecute).toHaveBeenCalledWith(
      'INSERT INTO adventures (id, name) VALUES ($1, $2)',
      ['test-generated-id'],
    );
    expect(adventureId).toBe('test-generated-id');
  });

  it('should create adventure with default name', async () => {
    // needs test to show name is generated by default
  });
});
