/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdventuresAdventureIdRouteImport } from './routes/adventures.$adventureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresAdventureIdRoute = AdventuresAdventureIdRouteImport.update({
  id: '/adventures/$adventureId',
  path: '/adventures/$adventureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventures/$adventureId': typeof AdventuresAdventureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventures/$adventureId': typeof AdventuresAdventureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventures/$adventureId': typeof AdventuresAdventureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adventures/$adventureId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adventures/$adventureId'
  id: '__root__' | '/' | '/adventures/$adventureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventuresAdventureIdRoute: typeof AdventuresAdventureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$adventureId': {
      id: '/adventures/$adventureId'
      path: '/adventures/$adventureId'
      fullPath: '/adventures/$adventureId'
      preLoaderRoute: typeof AdventuresAdventureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventuresAdventureIdRoute: AdventuresAdventureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
